import React, { useRef } from 'react'

function Section({ title, text }) {
  return (
    <div className="bg-slate-800/40 border border-blue-500/20 rounded-xl p-5">
      <h3 className="text-lg font-semibold text-white mb-3">{title}</h3>
      <pre className="whitespace-pre-wrap text-blue-100 text-sm leading-relaxed">{text}</pre>
    </div>
  )
}

function OutputViewer({ docs, onReset }) {
  const privacyRef = useRef(null)
  const termsRef = useRef(null)

  const download = (filename, text) => {
    const blob = new Blob([text], { type: 'text/plain;charset=utf-8' })
    const url = URL.createObjectURL(blob)
    const link = document.createElement('a')
    link.href = url
    link.download = filename
    document.body.appendChild(link)
    link.click()
    document.body.removeChild(link)
    URL.revokeObjectURL(url)
  }

  return (
    <div className="space-y-6">
      <div className="flex flex-col sm:flex-row gap-3 sm:items-center sm:justify-between">
        <h2 className="text-2xl font-bold text-white">Your Documents</h2>
        <div className="flex gap-2">
          <button onClick={() => download('privacy-policy.txt', docs.privacy_policy)} className="px-3 py-2 rounded bg-blue-500 text-white text-sm hover:bg-blue-600">Download Privacy Policy</button>
          <button onClick={() => download('terms-of-service.txt', docs.terms_of_service)} className="px-3 py-2 rounded bg-blue-500 text-white text-sm hover:bg-blue-600">Download Terms</button>
          <button onClick={onReset} className="px-3 py-2 rounded bg-slate-700 text-white text-sm hover:bg-slate-600">Generate Again</button>
        </div>
      </div>

      <Section title="Privacy Policy" text={docs.privacy_policy} ref={privacyRef} />
      <Section title="Terms of Service" text={docs.terms_of_service} ref={termsRef} />

      <p className="text-xs text-blue-200/70">
        Disclaimer: These are basic templates generated by AI and are not a substitute for legal advice. Consult a qualified attorney for guidance tailored to your situation.
      </p>
    </div>
  )
}

export default OutputViewer
